name: Android

on:
  push:
    branches: [ "main" ]

  pull_request:
    branches: [ "main" ]

  schedule:
    - cron: "30 03 * * 6"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: set up JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: gradle

      - name: Executable Permission
        run: chmod +x gradlew

      - name: Build Package
        run: ./gradlew clean build